name: ci

on:
  push:
  pull_request:
  schedule:
    - cron: "0 * * * *"

jobs:
  stable:
    name: Deno
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.3.0

      - name: Run deno test
        run: |
          deno --version
          deno run ./test.ts