name: test and build

on: [push, pull_request]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4.6
      - run: yarn install
      - run: yarn build
      - run: yarn test